/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TransitionEffect, TransitionStyle } from "@types/transition";
export { TransitionEffect, TransitionStyle } from "@types/transition";
export namespace Components {
    interface PicTransition {
        "active": boolean;
        "duration": number;
        "enter": string | TransitionStyle;
        "initial": string | TransitionStyle;
        "leave"?: string | TransitionStyle;
        "transitionEffect": TransitionEffect;
    }
}
declare global {
    interface HTMLPicTransitionElement extends Components.PicTransition, HTMLStencilElement {
    }
    var HTMLPicTransitionElement: {
        prototype: HTMLPicTransitionElement;
        new (): HTMLPicTransitionElement;
    };
    interface HTMLElementTagNameMap {
        "pic-transition": HTMLPicTransitionElement;
    }
}
declare namespace LocalJSX {
    interface PicTransition {
        "active"?: boolean;
        "duration"?: number;
        "enter"?: string | TransitionStyle;
        "initial"?: string | TransitionStyle;
        "leave"?: string | TransitionStyle;
        "transitionEffect"?: TransitionEffect;
    }
    interface IntrinsicElements {
        "pic-transition": PicTransition;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pic-transition": LocalJSX.PicTransition & JSXBase.HTMLAttributes<HTMLPicTransitionElement>;
        }
    }
}
